### ISSUE TITLE
Crash report: Org null 

### ISSUE THREAD

**Issue by norkans7** [rapidpro/surveyor#20]
```java
E/Surveyor(13342): Error running flow
E/Surveyor(13342): java.lang.NullPointerException: Attempt to invoke virtual method 'int io.rapidpro.surveyor.data.DBOrg.getId()' on a nul\
l object reference
E/Surveyor(13342): at io.rapidpro.surveyor.activity.FlowRunActivity$4.resolve(FlowRunActivity.java:210)
E/Surveyor(13342): at io.rapidpro.flows.runner.Runner.parseLocation(Runner.java:223)
E/Surveyor(13342): at io.rapidpro.flows.definition.tests.location.HasStateTest.evaluate(HasStateTest.java:40)
E/Surveyor(13342): at io.rapidpro.flows.definition.Rule.matches(Rule.java:50)
E/Surveyor(13342): at io.rapidpro.flows.definition.RuleSet.findMatchingRule(RuleSet.java:154)
E/Surveyor(13342): at io.rapidpro.flows.definition.RuleSet.visit(RuleSet.java:111)
E/Surveyor(13342): at io.rapidpro.flows.runner.Runner.resume(Runner.java:162)
E/Surveyor(13342): at io.rapidpro.surveyor.activity.FlowRunActivity.sendMessage(FlowRunActivity.java:321)
E/Surveyor(13342): at java.lang.reflect.Method.invoke(Native Method)
E/Surveyor(13342): at java.lang.reflect.Method.invoke(Method.java:372)
E/Surveyor(13342): at android.view.View$1.onClick(View.java:4150)
E/Surveyor(13342): at android.view.View.performClick(View.java:5106)
E/Surveyor(13342): at android.view.View$PerformClick.run(View.java:20329)
E/Surveyor(13342): at android.os.Handler.handleCallback(Handler.java:739)
E/Surveyor(13342): at android.os.Handler.dispatchMessage(Handler.java:95)
E/Surveyor(13342): at android.os.Looper.loop(Looper.java:135)
E/Surveyor(13342): at android.app.ActivityThread.main(ActivityThread.java:5912)
E/Surveyor(13342): at java.lang.reflect.Method.invoke(Native Method)
E/Surveyor(13342): at java.lang.reflect.Method.invoke(Method.java:372)
E/Surveyor(13342): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
E/Surveyor(13342): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

**Comment by norkans7** [comment]
First approach in https://github.com/rapidpro/surveyor/pull/19
