### ISSUE TITLE
Crashed on Android4.4

### ISSUE THREAD

**Issue by zhendong2050** [rapidpro/surveyor#66]
Hi I need to run surveyor on Android 4.4 but the app crashed with the following error. Can you give some suggestion for fixing this?

java.lang.NoClassDefFoundError: androidx.core.content.FileProvider$PathStrategy
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:576)
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:392)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4771)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4366)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4306)
        at android.app.ActivityThread.access$1400(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1457)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:5013)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by rowanseymour** [comment]
Hmm Android 4.4 (SDK 19) is the current minimum supported version so it should work.. but I just tried running the tests and ran into a different problem supposedly caused by using latest Android Studio and SDKs < 21

**Comment by zhendong2050** [comment]
@rowanseymour Thanks for the fast reply. I want to explore the app but cannot register an account. Can I have a faked account for testing the app? Thank you.

**Comment by rowanseymour** [comment]
You can create an account on textit.com that's open to anyone and there's a TextIt Surveyor version of the app in the play store. You can also change the URL in the code if you're debugging that.
