### ISSUE TITLE
Google API Client causes crash

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/surveyor#8]
Failure to connection GoogleApiClient causes crash. This is for location fetching flows on only a handful of devices / accounts

Stack trace:
> java.lang.IllegalStateException: GoogleApiClient is not connected yet.
E/AndroidRuntime(23481): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3345)
E/AndroidRuntime(23481): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3292)
E/AndroidRuntime(23481): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3267)
E/AndroidRuntime(23481): 	at android.app.ActivityThread.access$1000(ActivityThread.java:155)
E/AndroidRuntime(23481): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
E/AndroidRuntime(23481): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(23481): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(23481): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(23481): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23481): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(23481): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(23481): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(23481): Caused by: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
E/AndroidRuntime(23481): 	at com.google.android.gms.internal.zzoe.zzd(Unknown Source)
E/AndroidRuntime(23481): 	at com.google.android.gms.internal.zzoh.zzd(Unknown Source)
E/AndroidRuntime(23481): 	at com.google.android.gms.internal.zzof.zzd(Unknown Source)
E/AndroidRuntime(23481): 	at com.google.android.gms.location.internal.zzd.removeLocationUpdates(Unknown Source)
E/AndroidRuntime(23481): 	at io.rapidpro.surveyor.activity.FlowRunActivity.stopLocationUpdates(FlowRunActivity.java:531)
E/AndroidRuntime(23481): 	at io.rapidpro.surveyor.activity.FlowRunActivity.onPause(FlowRunActivity.java:271)
E/AndroidRuntime(23481): 	at android.app.Activity.performPause(Activity.java:6121)
E/AndroidRuntime(23481): 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1333)
E/AndroidRuntime(23481): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3325)

**Comment by ericnewcomer** [comment]
Fixed in https://github.com/rapidpro/surveyor/commit/b0b5f29403b7019fd55ce5d2ad0aefc73b9e6db7
